torchrun --nnodes 1 --nproc_per_node 1 recipes/finetuning/real_finetuning_player_classification.py \
  --lr 3e-4 \
  --val_batch_size 22 \
  --run_validation True \
  --validation_interval 399 \
  --save_metrics True \
  --dist_checkpoint_root_folder "models/music_classification-v0/checkpoints" \
  --dist_checkpoint_folder ddp \
  --trained_checkpoint_path "models/pretrained/moonbeam_839M.pt" \
  --pure_bf16 True \
  --enable_ddp True \
  --use_peft True \
  --peft_method lora \
  --quantization False \
  --model_name "player_classification_dataset" \
  --dataset "player_classification_dataset" \
  --output_dir "models/music_classification-v0" \
  --batch_size_training 1 \
  --context_length 1203 \
  --num_epochs 300 \
  --use_wandb True \
  --use_cache False \
  --individual_eval True


torchrun --nnodes 1 --nproc_per_node 1 recipes/finetuning/real_finetuning_player_classification.py \
  --lr 3e-4 \
  --val_batch_size 22 \
  --run_validation True \
  --validation_interval 399 \
  --save_metrics True \
  --dist_checkpoint_root_folder "models/music_classification-v0/checkpoints" \
  --dist_checkpoint_folder ddp \
  --trained_checkpoint_path "models/pretrained/moonbeam_839M.pt" \
  --pure_bf16 True \
  --enable_ddp True \
  --use_peft True \
  --peft_method lora \
  --quantization False \
  --model_name "player_classification_dataset" \
  --dataset "player_classification_dataset" \
  --output_dir "models/music_classification-v0" \
  --batch_size_training 1 \
  --context_length 1203 \
  --num_epochs 300 \
  --use_wandb True \
  --use_cache False \
  --individual_eval True
